### ISSUE TITLE
Не хватает сортировки при вызове /percentstats

### ISSUE THREAD

**Issue by ShayMarGen** [Strelkoveg/BetterUserOfTheDay#1]
![image](https://github.com/Strelkoveg/BetterUserOfTheDay/assets/130654773/5743ee5c-a01f-49e1-a561-df9a770d9872)

Хотелось бы сортировку по красавчиковости :)

**Comment by Strelkoveg** [comment]
Сделал сортировку по возрастанию по красавчику.
